name: Site tests

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    name: Site tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install imagemagick libcurl4-openssl-dev libssl-dev

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flake8 coverage
          pip install -r requirements.txt --use-feature=2020-resolver

      - name: Test
        working-directory: ./prologin
        env:
          DJANGO_SETTINGS_MODULE: prologin.settings.test
        run: |
          python3 -m coverage run --source='.' manage.py test -v2
          python3 -m coverage xml

      # Re-enable when site can be linted properly.
      #
      # - name: Lint with flake8
      #   working-directory: ./tools/generator
      #   run: |
      #     flake8 . --count --show-source --statistics

      - name: Coverage upload to Codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          file: ./prologin/coverage.xml
          name: site
          fail_ci_if_error: true
